#-------------------------------------------------------------------------------
# Note for using the rate-limiting:
#   The comment part won't be copied if you use the subgenerator docker-compose
#   you have to manually copy it
#-------------------------------------------------------------------------------
version: '2'
services:
    tnggui-app:
        image: tnggui
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@tnggui-oracle:1521:tnggui
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=tnggui-cassandra
            - JHIPSTER_SLEEP=30 # gives time for the Cassandra cluster to start and execute the migration scripts
        ports:
            - 8080:8080
    # Uncomment to have Cassandra working with the gateway
    # tnggui-cassandra:
    #     extends:
    #         file: cassandra-cluster.yml
    #         service: tnggui-cassandra
    # tnggui-cassandra-migration:
    #     extends:
    #         file: cassandra-migration.yml
    #         service: tnggui-cassandra-migration
    #     environment:
    #         - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
